version: "2.2"

services:
  postgresdb:
    image: postgres:14
    env_file:
      - .env
    environment:
      PGUSER: ${APPLICATION_DB_USER}
      POSTGRES_USER: ${APPLICATION_DB_USER}
      POSTGRES_PASSWORD: ${APPLICATION_DB_PASSWORD}
    volumes:
      - ${APPLICATION_DB_MOUNT_PATH}:/var/lib/postgresql/data
    ports:
      - ${APPLICATION_DB_EXTERNAL_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 40s
      retries: 6
  
  
  migrations:
    image: registry.digitalocean.com/smokeisland/migrations:beta
    restart: on-failure
    env_file:
      - .env
    depends_on:
      postgresdb:
          condition: service_healthy
    healthcheck:
      test: [ "CMD", "sh", "/app/health_check.sh" ]
      interval: 5s
      retries: 30
  
  application:
    image: registry.digitalocean.com/smokeisland/application:beta
    restart: unless-stopped
    env_file:
      - .env 
    depends_on:
      migrations:
          condition: service_healthy
    volumes:
      - ${APPLICATION_CERT_MOUNT_PATH}:${APPLICATION_INTERNAL_CERT_PATH}
    ports:
      - ${APPLICATION_HTTP_EXTERNAL_PORT}:55525
      - ${APPLICATION_HTTPS_EXTERNAL_PORT}:55526
    
